### ISSUE TITLE
add "copy to clipboard " feature

### ISSUE THREAD

**Issue by join2akshay** [elharony/Google-Fonts-Previewer#6]
hey!!!! @elharony  first thing  is this tool is amazing.I saved this tool in my bookmark for my personal use.
but i want a feature in this tool which is "copy to clipborad" feature.  it will copy the `Embed Font Link`  which we can use in our local projects.

**Comment by elharony** [comment]
Thanks for your interest in the tool.
You've mentioned a great feature, and I like that you did it yourself... I've merged your #7 PR, cheers! 🎉 

Can't wait to see more contributions.
